server {
    listen 8080;
    server_name _;

    client_max_body_size 40m;

    location /glitchtip/ {
        proxy_pass http://glitchtip-web:8000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Prefix /glitchtip;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Accept-Encoding "";

        sub_filter '<base href="/"/>' '<base href="/glitchtip/"/>';
        sub_filter_once on;
        sub_filter_types text/html;
    }
}
