// Objective-C API for talking to github.com/skrashevich/encx-cli/mobile/encxmobile Go package.
//   gobind -lang=objc github.com/skrashevich/encx-cli/mobile/encxmobile
//
// File is generated by gobind. Do not edit.

#ifndef __Encxmobile_H__
#define __Encxmobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class EncxmobileEncClient;
@class EncxmobileHARSnapshot;

/**
 * EncClient wraps encx.Client for use from iOS via gomobile.
 */
@interface EncxmobileEncClient : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * AcceptTeamInvitation accepts a team invitation.
 */
- (BOOL)acceptTeamInvitation:(int64_t)teamID error:(NSError* _Nullable* _Nullable)error;
/**
 * ClearHAR removes all captured HAR entries.
 */
- (void)clearHAR;
/**
 * ClearHARFirst removes the n oldest captured HAR entries.
 */
- (void)clearHARFirst:(int64_t)n;
/**
 * Domain returns the configured Encounter domain.
 */
- (NSString* _Nonnull)domain;
/**
 * EnterGame registers the player in a game. Returns raw server response.
 */
- (NSString* _Nonnull)enterGame:(int64_t)gameID error:(NSError* _Nullable* _Nullable)error;
/**
 * ExportCookies serializes session cookies to JSON bytes for persistent storage.
 */
- (NSData* _Nullable)exportCookies:(NSError* _Nullable* _Nullable)error;
/**
 * ExportHAR returns captured traffic as a HAR 1.2 JSON document.
 */
- (NSString* _Nonnull)exportHAR:(NSError* _Nullable* _Nullable)error;
/**
 * ExportHARSnapshot atomically exports captured traffic together with its
entry count; pass the count to ClearHARFirst after a successful upload so
entries captured during the upload are preserved.
 */
- (EncxmobileHARSnapshot* _Nullable)exportHARSnapshot:(NSError* _Nullable* _Nullable)error;
/**
 * GetDomainGames returns games parsed from the domain main page as JSON array.
 */
- (NSString* _Nonnull)getDomainGames:(NSError* _Nullable* _Nullable)error;
/**
 * GetGameDetails returns the game details page HTML.
 */
- (NSString* _Nonnull)getGameDetails:(int64_t)gameID error:(NSError* _Nullable* _Nullable)error;
/**
 * GetGameList returns ComingGames and ActiveGames as JSON. page is 1-based (0 = first page).
 */
- (NSString* _Nonnull)getGameList:(int64_t)page error:(NSError* _Nullable* _Nullable)error;
/**
 * GetGameModel returns the current game state as GameModel JSON.
 */
- (NSString* _Nonnull)getGameModel:(int64_t)gameID error:(NSError* _Nullable* _Nullable)error;
/**
 * GetGameModelLevel returns the state for a specific level number in storm sequence games.
 */
- (NSString* _Nonnull)getGameModelLevel:(int64_t)gameID levelNumber:(int64_t)levelNumber error:(NSError* _Nullable* _Nullable)error;
/**
 * GetGameStatistics returns full game statistics as JSON.
 */
- (NSString* _Nonnull)getGameStatistics:(int64_t)gameID error:(NSError* _Nullable* _Nullable)error;
/**
 * GetMyTeamDetails returns the current user's team page HTML.
 */
- (NSString* _Nonnull)getMyTeamDetails:(NSError* _Nullable* _Nullable)error;
/**
 * GetPenaltyHint requests a penalty hint. Returns updated GameModel JSON.
 */
- (NSString* _Nonnull)getPenaltyHint:(int64_t)gameID penaltyID:(int64_t)penaltyID error:(NSError* _Nullable* _Nullable)error;
/**
 * GetProfile returns the current user profile as JSON.
 */
- (NSString* _Nonnull)getProfile:(NSError* _Nullable* _Nullable)error;
/**
 * GetTeamDetails returns team details page HTML.
 */
- (NSString* _Nonnull)getTeamDetails:(int64_t)teamID error:(NSError* _Nullable* _Nullable)error;
/**
 * GetTeamInvitations returns team invitations addressed to the current user as JSON.
 */
- (NSString* _Nonnull)getTeamInvitations:(NSError* _Nullable* _Nullable)error;
/**
 * GetTeamManagementInfo returns parsed team management info as JSON.
 */
- (NSString* _Nonnull)getTeamManagementInfo:(int64_t)teamID error:(NSError* _Nullable* _Nullable)error;
/**
 * GetTimeoutToGame returns seconds until game start, or -1 if no counter is present.
 */
- (BOOL)getTimeoutToGame:(int64_t)gameID ret0_:(int64_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
/**
 * HAREntryCount returns the number of captured HAR entries.
 */
- (int64_t)harEntryCount;
/**
 * ImportCookies restores session cookies from JSON bytes produced by ExportCookies.
 */
- (BOOL)importCookies:(NSData* _Nullable)data error:(NSError* _Nullable* _Nullable)error;
/**
 * InviteTeamMember invites a user login into a team.
 */
- (BOOL)inviteTeamMember:(int64_t)teamID login:(NSString* _Nullable)login error:(NSError* _Nullable* _Nullable)error;
/**
 * LeaveTeam leaves a team when TeamDetails.aspx exposes a leave action.
 */
- (BOOL)leaveTeam:(int64_t)teamID error:(NSError* _Nullable* _Nullable)error;
/**
 * Login authenticates on the Encounter domain. Returns LoginResponse JSON.
 */
- (NSString* _Nonnull)login:(NSString* _Nullable)login password:(NSString* _Nullable)password error:(NSError* _Nullable* _Nullable)error;
/**
 * LoginWithCaptcha authenticates with CAPTCHA digits when Login returns Error==1.
 */
- (NSString* _Nonnull)loginWithCaptcha:(NSString* _Nullable)login password:(NSString* _Nullable)password magicNumbers:(NSString* _Nullable)magicNumbers error:(NSError* _Nullable* _Nullable)error;
/**
 * PingGame checks engine reachability with the code-send timeout.
 */
- (NSString* _Nonnull)pingGame:(int64_t)gameID error:(NSError* _Nullable* _Nullable)error;
/**
 * RejectTeamInvitation rejects a team invitation.
 */
- (BOOL)rejectTeamInvitation:(int64_t)teamID error:(NSError* _Nullable* _Nullable)error;
/**
 * RemoveTeamInvitation removes a pending invitation sent by a team.
 */
- (BOOL)removeTeamInvitation:(int64_t)teamID userID:(int64_t)userID error:(NSError* _Nullable* _Nullable)error;
/**
 * RenameTeam renames a team.
 */
- (BOOL)renameTeam:(int64_t)teamID name:(NSString* _Nullable)name error:(NSError* _Nullable* _Nullable)error;
/**
 * RequestTeamMembership sends a request to join a team by name.
 */
- (BOOL)requestTeamMembership:(NSString* _Nullable)teamName error:(NSError* _Nullable* _Nullable)error;
/**
 * SendBonusCode submits a bonus answer via BonusAction.Answer. Returns updated GameModel JSON.
 */
- (NSString* _Nonnull)sendBonusCode:(int64_t)gameID levelID:(int64_t)levelID levelNumber:(int64_t)levelNumber code:(NSString* _Nullable)code error:(NSError* _Nullable* _Nullable)error;
/**
 * SendCode submits an answer via LevelAction.Answer. Returns updated GameModel JSON.
 */
- (NSString* _Nonnull)sendCode:(int64_t)gameID levelID:(int64_t)levelID levelNumber:(int64_t)levelNumber code:(NSString* _Nullable)code error:(NSError* _Nullable* _Nullable)error;
/**
 * SetCodeSendTimeoutSeconds sets the per-request timeout for code submissions and quick probes.
Zero or negative values reset to the default (1 second).
 */
- (void)setCodeSendTimeoutSeconds:(int64_t)seconds;
/**
 * SetGameRequestMinIntervalMillis sets the minimum interval between mobile game-engine requests.
Zero or negative values disable pacing.
 */
- (void)setGameRequestMinIntervalMillis:(int64_t)milliseconds;
/**
 * SetHARRecordingEnabled toggles HAR 1.2 capture for Encounter HTTP traffic.
 */
- (void)setHARRecordingEnabled:(BOOL)enabled;
/**
 * SetTeamForum updates the team external forum URL.
 */
- (BOOL)setTeamForum:(int64_t)teamID forum:(NSString* _Nullable)forum error:(NSError* _Nullable* _Nullable)error;
/**
 * SetTeamSite updates the team website URL.
 */
- (BOOL)setTeamSite:(int64_t)teamID site:(NSString* _Nullable)site error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * HARSnapshot pairs an exported HAR document with the number of entries it contains.
 */
@interface EncxmobileHARSnapshot : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull json;
@property (nonatomic) int64_t entryCount;
@end

/**
 * AntiSpamURLFromError returns the verification page URL when err is anti-spam.
 */
FOUNDATION_EXPORT NSString* _Nonnull EncxmobileAntiSpamURLFromError(NSError* _Nullable err);

/**
 * EventText returns a human-readable game event status description.
 */
FOUNDATION_EXPORT NSString* _Nonnull EncxmobileEventText(int64_t code);

/**
 * IsAntiSpamError reports whether err is an anti-spam (NotHumanRequest) challenge.
 */
FOUNDATION_EXPORT BOOL EncxmobileIsAntiSpamError(NSError* _Nullable err);

/**
 * LoginErrorText returns a human-readable login error description.
 */
FOUNDATION_EXPORT NSString* _Nonnull EncxmobileLoginErrorText(int64_t code);

/**
 * NewClient creates an Encounter API client for the given domain.
Set insecureTLS to true to skip TLS certificate verification (e.g. for tech.en.cx).
 */
FOUNDATION_EXPORT EncxmobileEncClient* _Nullable EncxmobileNewClient(NSString* _Nullable domain, BOOL insecureTLS);

/**
 * NewClientWithOptions creates a client with extended configuration.
timeoutSeconds: HTTP client timeout (0 = default 15s). lang: API language (empty = "ru").
 */
FOUNDATION_EXPORT EncxmobileEncClient* _Nullable EncxmobileNewClientWithOptions(NSString* _Nullable domain, BOOL insecureTLS, BOOL useHTTP, int64_t timeoutSeconds, NSString* _Nullable lang);

/**
 * ParseTeamInvitations extracts incoming team invitations from HTML. Returns JSON array.
 */
FOUNDATION_EXPORT NSString* _Nonnull EncxmobileParseTeamInvitations(NSString* _Nullable html, NSError* _Nullable* _Nullable error);

/**
 * ParseTeamLinks extracts team IDs and names from HTML. Returns JSON array of TeamInfo.
 */
FOUNDATION_EXPORT NSString* _Nonnull EncxmobileParseTeamLinks(NSString* _Nullable html, NSError* _Nullable* _Nullable error);

/**
 * ParseTeamManagementInfo extracts team management info from HTML. Returns JSON.
 */
FOUNDATION_EXPORT NSString* _Nonnull EncxmobileParseTeamManagementInfo(NSString* _Nullable html, int64_t teamID, NSError* _Nullable* _Nullable error);

#endif
