// Objective-C API for talking to github.com/skrashevich/encx-cli/mobile/encxmobile Go package.
//   gobind -lang=objc github.com/skrashevich/encx-cli/mobile/encxmobile
//
// File is generated by gobind. Do not edit.

#ifndef __Encxmobile_H__
#define __Encxmobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class EncxmobileAgentSession;
@class EncxmobileCodexDeviceLogin;
@class EncxmobileEncClient;
@class EncxmobileHARSnapshot;
@protocol EncxmobileAgentDelegate;
@class EncxmobileAgentDelegate;

@protocol EncxmobileAgentDelegate <NSObject>
/**
 * OnConfirmationRequest asks the host to authorize a mutating engine call.
The host must answer exactly once by calling ResolveConfirmation with the
same callID; until then the agent turn is blocked.

turn identifies the agent turn that raised the call. A host that keeps a
queue should drop requests from a turn that has already ended: the
notification is delivered asynchronously and can outlive its turn.
 */
- (void)onConfirmationRequest:(NSString* _Nullable)callID turn:(int64_t)turn toolName:(NSString* _Nullable)toolName argsJSON:(NSString* _Nullable)argsJSON;
/**
 * OnEvent delivers a JSON-encoded progress event. See AgentSession for the
event shapes.
 */
- (void)onEvent:(NSString* _Nullable)eventJSON;
/**
 * OnLocationRequest asks the host for the device's current GPS position. The
host must answer exactly once by calling ResolveLocation or FailLocation
with the same requestID; until then the tool call is blocked.

turn plays the same role as in OnConfirmationRequest: a host that queues
requests should drop those from a turn that has already ended.
 */
- (void)onLocationRequest:(NSString* _Nullable)requestID turn:(int64_t)turn;
@end

/**
 * AgentSession is a PicoClaw agent wired to one Encounter client.

Progress reaches the host as JSON events through AgentDelegate.OnEvent. Every
event has a "type" and a "turn" field:

	{"type":"turn_started","turn":1}
	{"type":"tool_started","turn":1,"tool":"enc_game_state","args":{"game_id":42}}
	{"type":"tool_finished","turn":1,"tool":"enc_game_state","is_error":false,"result":"…"}
	{"type":"turn_finished","turn":1,"content":"…"}
	{"type":"turn_failed","turn":1,"error":"…"}

Mutating tools do not emit an event; they call OnConfirmationRequest and wait.
 */
@interface EncxmobileAgentSession : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Cancel aborts the running turn. SendMessage then returns the cancellation
error and any pending confirmation is released as declined.
 */
- (void)cancel;
/**
 * CodexCredentialJSON returns the current ChatGPT credential so the host can
persist a token that was refreshed during the session. It returns an empty
string for sessions that authenticate with an API key.
 */
- (NSString* _Nonnull)codexCredentialJSON:(NSError* _Nullable* _Nullable)error;
/**
 * FailLocation reports that the host cannot provide a position — permission
denied, location services off, or no fix. The message reaches the model, so
it should say why in plain words.
 */
- (BOOL)failLocation:(NSString* _Nullable)requestID message:(NSString* _Nullable)message error:(NSError* _Nullable* _Nullable)error;
/**
 * HistoryJSON returns the remembered transcript as a JSON array of
{"role","content"} objects.
 */
- (NSString* _Nonnull)historyJSON:(NSError* _Nullable* _Nullable)error;
/**
 * Policy reports the engine access policy the session was built with.
 */
- (NSString* _Nonnull)policy;
/**
 * ResetHistory forgets the transcript without rebuilding the session.
 */
- (void)resetHistory;
/**
 * ResolveConfirmation delivers the host's decision for a mutating call.
 */
- (BOOL)resolveConfirmation:(NSString* _Nullable)callID approved:(BOOL)approved error:(NSError* _Nullable* _Nullable)error;
/**
 * ResolveLocation delivers the device position for a pending location request.
locationJSON is passed to the model verbatim; the host decides the fields
(latitude, longitude, accuracy and so on).
 */
- (BOOL)resolveLocation:(NSString* _Nullable)requestID locationJSON:(NSString* _Nullable)locationJSON error:(NSError* _Nullable* _Nullable)error;
/**
 * SendMessage runs one agent turn and returns the assistant's reply.

Only the visible transcript is remembered between turns. Tool output is
deliberately not replayed: game state changes while the player reads, so a
cached level or code log would be worse than a fresh read.
 */
- (NSString* _Nonnull)sendMessage:(NSString* _Nullable)text error:(NSError* _Nullable* _Nullable)error;
/**
 * SetDelegate attaches (or, with nil, detaches) the host callbacks.
 */
- (void)setDelegate:(id<EncxmobileAgentDelegate> _Nullable)delegate;
/**
 * ToolCount reports how many engine tools the model can see.
 */
- (int64_t)toolCount;
@end

/**
 * CodexDeviceLogin drives the ChatGPT device-authorization flow.

The device flow suits a phone: there is no redirect URI to catch and no local
callback listener to run. The app shows UserCode, sends the player to
VerifyURL in a browser, and polls until they approve.

Usage from Swift:

	login, err := StartCodexDeviceLogin()
	// show login.UserCode(), open login.VerifyURL()
	credentialJSON, err := login.Wait(300)   // blocking; call off the main thread
	// store credentialJSON in the Keychain, pass it back in the agent config
 */
@interface EncxmobileCodexDeviceLogin : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Cancel stops a running Wait.
 */
- (void)cancel;
/**
 * IntervalSeconds is the polling interval OpenAI asked for.
 */
- (int64_t)intervalSeconds;
/**
 * Poll checks once whether the player has approved. It returns the credential
JSON on success and an empty string while the approval is still pending.

The upstream endpoint reports "not approved yet" as an HTTP error, which
PicoClaw surfaces as a bare "pending" error, so that one is translated back
into the pending state instead of being shown to the player as a failure.
 */
- (NSString* _Nonnull)poll:(NSError* _Nullable* _Nullable)error;
/**
 * UserCode is the code the player types on the verification page.
 */
- (NSString* _Nonnull)userCode;
/**
 * VerifyURL is the page where the player approves the login.
 */
- (NSString* _Nonnull)verifyURL;
/**
 * Wait polls until the player approves, the timeout expires, or Cancel is
called. It blocks, so callers must keep it off the UI thread.

Transient poll failures do not abort the login: the player is in another app
and cannot react to them. The last one is reported only if the wait runs out.
 */
- (NSString* _Nonnull)wait:(int64_t)timeoutSeconds error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * EncClient wraps encx.Client for use from iOS via gomobile.
 */
@interface EncxmobileEncClient : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * APIBaseURL returns the host the new engine is reached at.
 */
- (NSString* _Nonnull)apiBaseURL;
/**
 * AcceptTeamInvitation accepts a team invitation.
 */
- (BOOL)acceptTeamInvitation:(int64_t)teamID error:(NSError* _Nullable* _Nullable)error;
- (BOOL)adminCreateGame:(NSString* _Nullable)paramsJSON ret0_:(int64_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
/**
 * ClearHAR removes all captured HAR entries.
 */
- (void)clearHAR;
/**
 * ClearHARFirst removes the n oldest captured HAR entries.
 */
- (void)clearHARFirst:(int64_t)n;
/**
 * Domain returns the configured Encounter domain.
 */
- (NSString* _Nonnull)domain;
/**
 * Engine reports which backend is actually serving this client.
 */
- (NSString* _Nonnull)engine;
/**
 * EnterGame registers the player in a game. Returns raw server response.
 */
- (NSString* _Nonnull)enterGame:(int64_t)gameID error:(NSError* _Nullable* _Nullable)error;
/**
 * ExportCookies serializes session cookies to JSON bytes for persistent storage.
 */
- (NSData* _Nullable)exportCookies:(NSError* _Nullable* _Nullable)error;
/**
 * ExportHAR returns captured traffic as a HAR 1.2 JSON document.
 */
- (NSString* _Nonnull)exportHAR:(NSError* _Nullable* _Nullable)error;
/**
 * ExportHARSnapshot atomically exports captured traffic together with its
entry count; pass the count to ClearHARFirst after a successful upload so
entries captured during the upload are preserved.
 */
- (EncxmobileHARSnapshot* _Nullable)exportHARSnapshot:(NSError* _Nullable* _Nullable)error;
/**
 * GetDomainGames returns games parsed from the domain main page as JSON array.
 */
- (NSString* _Nonnull)getDomainGames:(NSError* _Nullable* _Nullable)error;
/**
 * GetGameDetails returns the game details page HTML.
 */
- (NSString* _Nonnull)getGameDetails:(int64_t)gameID error:(NSError* _Nullable* _Nullable)error;
/**
 * GetGameList returns ComingGames and ActiveGames as JSON. page is 1-based (0 = first page).
 */
- (NSString* _Nonnull)getGameList:(int64_t)page error:(NSError* _Nullable* _Nullable)error;
/**
 * GetGameModel returns the current game state as GameModel JSON.
 */
- (NSString* _Nonnull)getGameModel:(int64_t)gameID error:(NSError* _Nullable* _Nullable)error;
/**
 * GetGameModelLevel returns the state for a specific level number in storm sequence games.
 */
- (NSString* _Nonnull)getGameModelLevel:(int64_t)gameID levelNumber:(int64_t)levelNumber error:(NSError* _Nullable* _Nullable)error;
/**
 * GetGameStatistics returns full game statistics as JSON.
 */
- (NSString* _Nonnull)getGameStatistics:(int64_t)gameID error:(NSError* _Nullable* _Nullable)error;
/**
 * GetMyTeamDetails returns the current user's team page HTML.
 */
- (NSString* _Nonnull)getMyTeamDetails:(NSError* _Nullable* _Nullable)error;
/**
 * GetPenaltyHint requests a penalty hint. Returns updated GameModel JSON.
 */
- (NSString* _Nonnull)getPenaltyHint:(int64_t)gameID penaltyID:(int64_t)penaltyID error:(NSError* _Nullable* _Nullable)error;
/**
 * GetProfile returns the current user profile as JSON.
 */
- (NSString* _Nonnull)getProfile:(NSError* _Nullable* _Nullable)error;
/**
 * GetTeamDetails returns team details page HTML.
 */
- (NSString* _Nonnull)getTeamDetails:(int64_t)teamID error:(NSError* _Nullable* _Nullable)error;
/**
 * GetTeamInvitations returns team invitations addressed to the current user as JSON.
 */
- (NSString* _Nonnull)getTeamInvitations:(NSError* _Nullable* _Nullable)error;
/**
 * GetTeamManagementInfo returns parsed team management info as JSON.
 */
- (NSString* _Nonnull)getTeamManagementInfo:(int64_t)teamID error:(NSError* _Nullable* _Nullable)error;
/**
 * GetTimeoutToGame returns seconds until game start, or -1 if no counter is present.
 */
- (BOOL)getTimeoutToGame:(int64_t)gameID ret0_:(int64_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
/**
 * HAREntryCount returns the number of captured HAR entries.
 */
- (int64_t)harEntryCount;
/**
 * ImportCookies restores session cookies from JSON bytes produced by ExportCookies.
 */
- (BOOL)importCookies:(NSData* _Nullable)data error:(NSError* _Nullable* _Nullable)error;
/**
 * InviteTeamMember invites a user login into a team.
 */
- (BOOL)inviteTeamMember:(int64_t)teamID login:(NSString* _Nullable)login error:(NSError* _Nullable* _Nullable)error;
/**
 * LeaveTeam leaves a team when TeamDetails.aspx exposes a leave action.
 */
- (BOOL)leaveTeam:(int64_t)teamID error:(NSError* _Nullable* _Nullable)error;
/**
 * Login authenticates on the Encounter domain. Returns LoginResponse JSON.
 */
- (NSString* _Nonnull)login:(NSString* _Nullable)login password:(NSString* _Nullable)password error:(NSError* _Nullable* _Nullable)error;
/**
 * LoginWithCaptcha authenticates with CAPTCHA digits when Login returns Error==1.
 */
- (NSString* _Nonnull)loginWithCaptcha:(NSString* _Nullable)login password:(NSString* _Nullable)password magicNumbers:(NSString* _Nullable)magicNumbers error:(NSError* _Nullable* _Nullable)error;
- (EncxmobileAgentSession* _Nullable)newAgentSession:(NSString* _Nullable)configJSON error:(NSError* _Nullable* _Nullable)error;
/**
 * PingGame checks engine reachability with the code-send timeout.
 */
- (NSString* _Nonnull)pingGame:(int64_t)gameID error:(NSError* _Nullable* _Nullable)error;
/**
 * RejectTeamInvitation rejects a team invitation.
 */
- (BOOL)rejectTeamInvitation:(int64_t)teamID error:(NSError* _Nullable* _Nullable)error;
/**
 * RemoveTeamInvitation removes a pending invitation sent by a team.
 */
- (BOOL)removeTeamInvitation:(int64_t)teamID userID:(int64_t)userID error:(NSError* _Nullable* _Nullable)error;
/**
 * RenameTeam renames a team.
 */
- (BOOL)renameTeam:(int64_t)teamID name:(NSString* _Nullable)name error:(NSError* _Nullable* _Nullable)error;
/**
 * RequestTeamMembership sends a request to join a team by name.
 */
- (BOOL)requestTeamMembership:(NSString* _Nullable)teamName error:(NSError* _Nullable* _Nullable)error;
/**
 * SendBonusCode submits a bonus answer via BonusAction.Answer. Returns updated GameModel JSON.
 */
- (NSString* _Nonnull)sendBonusCode:(int64_t)gameID levelID:(int64_t)levelID levelNumber:(int64_t)levelNumber code:(NSString* _Nullable)code error:(NSError* _Nullable* _Nullable)error;
/**
 * SendCode submits an answer via LevelAction.Answer. Returns updated GameModel JSON.
 */
- (NSString* _Nonnull)sendCode:(int64_t)gameID levelID:(int64_t)levelID levelNumber:(int64_t)levelNumber code:(NSString* _Nullable)code error:(NSError* _Nullable* _Nullable)error;
/**
 * SetCodeSendTimeoutSeconds sets the per-request timeout for code submissions and quick probes.
Zero or negative values reset to the default (1 second).
 */
- (void)setCodeSendTimeoutSeconds:(int64_t)seconds;
/**
 * SetEngine selects the Encounter backend: "legacy" (default), "new", or
"auto" to probe the API host once. Unknown values are ignored so a caller
cannot silently end up on the wrong engine.

Encounter is migrating from the ASP.NET engine to a REST one; both are
implemented, and every method of this client works the same on either.
 */
- (void)setEngine:(NSString* _Nullable)mode;
/**
 * SetGameRequestMinIntervalMillis sets the minimum interval between mobile game-engine requests.
Zero or negative values disable pacing.
 */
- (void)setGameRequestMinIntervalMillis:(int64_t)milliseconds;
/**
 * SetHARRecordingEnabled toggles HAR 1.2 capture for Encounter HTTP traffic.
 */
- (void)setHARRecordingEnabled:(BOOL)enabled;
/**
 * SetTeamForum updates the team external forum URL.
 */
- (BOOL)setTeamForum:(int64_t)teamID forum:(NSString* _Nullable)forum error:(NSError* _Nullable* _Nullable)error;
/**
 * SetTeamSite updates the team website URL.
 */
- (BOOL)setTeamSite:(int64_t)teamID site:(NSString* _Nullable)site error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * HARSnapshot pairs an exported HAR document with the number of entries it contains.
 */
@interface EncxmobileHARSnapshot : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull json;
@property (nonatomic) int64_t entryCount;
@end

/**
 * AuthMethodCodex selects a ChatGPT subscription instead of an API key.
 */
FOUNDATION_EXPORT NSString* _Nonnull const EncxmobileAuthMethodCodex;

/**
 * AntiSpamURLFromError returns the verification page URL when err is anti-spam.
 */
FOUNDATION_EXPORT NSString* _Nonnull EncxmobileAntiSpamURLFromError(NSError* _Nullable err);

/**
 * EventText returns a human-readable game event status description.
 */
FOUNDATION_EXPORT NSString* _Nonnull EncxmobileEventText(int64_t code);

/**
 * IsAntiSpamError reports whether err is an anti-spam (NotHumanRequest) challenge.
 */
FOUNDATION_EXPORT BOOL EncxmobileIsAntiSpamError(NSError* _Nullable err);

/**
 * IsGameNotFoundError reports whether err says the domain does not host the requested game
(wrong game id, or a game that lives on another domain). This is permanent: retrying or
re-logging in cannot make the game appear, so the app should point at the domain instead.
 */
FOUNDATION_EXPORT BOOL EncxmobileIsGameNotFoundError(NSError* _Nullable err);

/**
 * IsUndecodableAcceptedError reports whether err is an unreadable reply from a 2xx response, i.e.
the request reached the engine and only the reply could not be parsed.

A submitted answer in that state was already recorded, so resending it would duplicate it.
Returns false for non-2xx bodies, where a proxy may have answered instead and the request may
never have arrived — those must stay retryable.
 */
FOUNDATION_EXPORT BOOL EncxmobileIsUndecodableAcceptedError(NSError* _Nullable err);

/**
 * LoginErrorText returns a human-readable login error description.
 */
FOUNDATION_EXPORT NSString* _Nonnull EncxmobileLoginErrorText(int64_t code);

/**
 * NewClient creates an Encounter API client for the given domain.
Set insecureTLS to true to skip TLS certificate verification (e.g. for tech.en.cx).
 */
FOUNDATION_EXPORT EncxmobileEncClient* _Nullable EncxmobileNewClient(NSString* _Nullable domain, BOOL insecureTLS);

/**
 * NewClientWithOptions creates a client with extended configuration.
timeoutSeconds: HTTP client timeout (0 = default 15s). lang: API language (empty = "ru").
 */
FOUNDATION_EXPORT EncxmobileEncClient* _Nullable EncxmobileNewClientWithOptions(NSString* _Nullable domain, BOOL insecureTLS, BOOL useHTTP, int64_t timeoutSeconds, NSString* _Nullable lang);

/**
 * ParseTeamInvitations extracts incoming team invitations from HTML. Returns JSON array.
 */
FOUNDATION_EXPORT NSString* _Nonnull EncxmobileParseTeamInvitations(NSString* _Nullable html, NSError* _Nullable* _Nullable error);

/**
 * ParseTeamLinks extracts team IDs and names from HTML. Returns JSON array of TeamInfo.
 */
FOUNDATION_EXPORT NSString* _Nonnull EncxmobileParseTeamLinks(NSString* _Nullable html, NSError* _Nullable* _Nullable error);

/**
 * ParseTeamManagementInfo extracts team management info from HTML. Returns JSON.
 */
FOUNDATION_EXPORT NSString* _Nonnull EncxmobileParseTeamManagementInfo(NSString* _Nullable html, int64_t teamID, NSError* _Nullable* _Nullable error);

/**
 * StartCodexDeviceLogin asks OpenAI for a device code.
 */
FOUNDATION_EXPORT EncxmobileCodexDeviceLogin* _Nullable EncxmobileStartCodexDeviceLogin(NSError* _Nullable* _Nullable error);

@class EncxmobileAgentDelegate;

/**
 * AgentDelegate is the host-side callback surface of an AgentSession. It is a
Go interface so Swift can implement it directly through the gomobile binding.
 */
@interface EncxmobileAgentDelegate : NSObject <goSeqRefInterface, EncxmobileAgentDelegate> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * OnConfirmationRequest asks the host to authorize a mutating engine call.
The host must answer exactly once by calling ResolveConfirmation with the
same callID; until then the agent turn is blocked.

turn identifies the agent turn that raised the call. A host that keeps a
queue should drop requests from a turn that has already ended: the
notification is delivered asynchronously and can outlive its turn.
 */
- (void)onConfirmationRequest:(NSString* _Nullable)callID turn:(int64_t)turn toolName:(NSString* _Nullable)toolName argsJSON:(NSString* _Nullable)argsJSON;
/**
 * OnEvent delivers a JSON-encoded progress event. See AgentSession for the
event shapes.
 */
- (void)onEvent:(NSString* _Nullable)eventJSON;
/**
 * OnLocationRequest asks the host for the device's current GPS position. The
host must answer exactly once by calling ResolveLocation or FailLocation
with the same requestID; until then the tool call is blocked.

turn plays the same role as in OnConfirmationRequest: a host that queues
requests should drop those from a turn that has already ended.
 */
- (void)onLocationRequest:(NSString* _Nullable)requestID turn:(int64_t)turn;
@end

#endif
