
// Objective-C API for talking to the following Go packages
//
//	github.com/skrashevich/encx-cli/mobile/encxmobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Encx_FRAMEWORK_H__
#define __Encx_FRAMEWORK_H__

#include "Encxmobile.objc.h"
#include "Universe.objc.h"

#endif
